parameters:
#    komodo_demo.example.class: Komodo\DemoBundle\Example

services:
#    komodo_demo.example:
#        class: %komodo_demo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
